[project]
name = "mkb10"
version = "0.2.0"
description = "Классификатор МКБ10 и МКБО"
readme = "README.rst"
requires-python = ">=3.12"
dependencies = [
    "flask==3.1.2",
    "gunicorn>=23.0.0",
    "peewee==3.18.3",
]
